project:
  type: website
  output-dir: docs

website:
  title: "Mathias Rask"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd
    right:
      - icon: github
        href: https://github.com/mraskj
      - icon: twitter
        href: https://twitter.com/mathiasrask95 

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

